### ISSUE TITLE
Simplify `sse` support in AsyncAPI specs

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#1151]
**Describe the desired outcome from the user's perspective**
As an AsyncAPI author, I want to be able to use Zilla to map sse to kafka using AsyncAPI v3 syntax.

**Acceptance criteria**
 - Syntax fits naturally with `http` AsyncAPI specs

**Additional context**
None

**Tasks**
 - [x] simplify to use `x-zilla-sse` operation binding instead of `sse` protocol
     - [x] update `asyncapi` binding accordingly
     - [ ] update `asyncapi` specs in `zilla-demos` etc
 - [ ] propose final `x-zilla-sse` syntax as `sse` support in AsyncAPI v3 spec
