### ISSUE TITLE
Support `kafka` server and client via `asyncapi`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#1317]
**Tasks**
 - [x] `asyncapi` `client` support for `kafka` protocol
 - [x] `kafka` `client` binding support
 - [ ] `asyncapi` `server` support for `kafka` protocol
 - [ ] `kafka` `server` binding support

Add an `asyncapi.proxy.kafka` scenario in `zilla-examples` illustrating `kafka` message validation.
