### ISSUE TITLE
`grpc-kafka` feature (baseline)

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#183]
### Baseline

 - `binding-grpc` assumes `http` network mapping to `grpc` application streams
   - [x] follow [grpc http2 wire protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) definition #171
 - `binding-grpc-kafka` maps `grpc` streams to `kafka` streams
   - [x] `grpc-kafka` mapping #184
     - route grpc `service` name and `method` name to kafka topic with reply-to
     - use hash of `grpc` request to generate `idempotency-key` if omitted from `metadata`
     - use grpc `idempotency-key` as injected kafka header `zilla:correlation-id`
   - [x] server streaming #186 
     - unreliable server streaming, similar to `sse-kafka` without `last-event-id`
     - reliable server streaming, similar to `sse-kafka` with `last-event-id`
 - `binding-kafka-grpc` maps `kafka` streams to `grpc` streams
   - [x] `kafka-grpc` mapping #185
     - route grpc `service` name and `method` name to kafka topic with reply-to
     - correlated request-response from `kafka` to `grpc` server
 - `zilla-examples`
   - [x] aklivity/zilla-examples#34 
   - [x] aklivity/zilla-examples#35 
   - [x] aklivity/zilla-examples#32 
   - [x] aklivity/zilla-examples#33
   - [x] aklivity/zilla-examples#36
