### ISSUE TITLE
Simplify configuration of multiple protocols on different tcp ports

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#669]
**Describe the desired outcome from the user's perspective**
As a developer, I want to reduce the number of bindings required in the pipeline to configure multiple protocols served on different tcp ports.

**Acceptance criteria**
 - unified `tcp` binding with ability to route by port
 - unified `tls` binding with ability to route by port

**Additional context**
None

**Tasks**
  - [x] https://github.com/aklivity/zilla/issues/294
  - [x] https://github.com/aklivity/zilla-docs/pull/72
  - [x] https://github.com/aklivity/zilla/issues/564
  - [x] https://github.com/aklivity/zilla-docs/pull/172

**Comment by lukefallows** [comment]
Im working on this.
