### ISSUE TITLE
Support incubator features preview in zilla release docker image

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#670]
**Describe the desired outcome from the user's perspective**
As a developer, I want to be able to try out zilla incubator features using the official zilla release, rather than having to build a local `develop-SNAPSHOT` docker image first.

**Acceptance criteria**
 - incubator feature implementations are included in zilla release docker image
 - incubator features are disabled by default in zilla release docker image
 - incubator features can be enabled when executing zilla commands
 - incubator features are no longer enabled by default for local builds
 - new incubator features are marked incubator by default until explicitly moved out of incubator

**Additional context**
None

**Tasks**
  - [ ] Allow each extensibility point to indicate if it is an incubator feature, `true` by default, overridden as needed
  - [ ] Engine discovers all extensibility points, but ignores incubator features if not enabled
  - [ ] EngineConfiguration to enable incubator features, `false` by default
  - [ ] ZillaCommand support to enable incubator features, including incubator commands
  - [ ] ZillaStartCommand configures Engine to enable to disable incubator features
  - [ ] ZillaMetricsCommand configures Engine to enable to disable incubator features
  - [ ] Unify incubator and release jammy Dockerfile, build alpine image on actual release
  - [ ] Update `zilla-examples` for incubator features to use `latest` docker image and enable incubator features
