### ISSUE TITLE
Support incremental validation of fragmented messages sent by client

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#671]
**Describe the desired outcome from the user's perspective**
Large messages are often fragmented into smaller partial messages, but should still be validated according to the same rules as if they are observed as a single unified value.

**Acceptance criteria**
 - Fragmented HTTP request messages can be validated or rejected; `string`, `integer`, `json`
 - Fragmented MQTT publish messages can be validated or rejected; `string`, `integer`, `json`
 - Fragmented Kafka produce messages can be validated or rejected; `string`, `integer`, `json`
 - Fragmented messages should _not_ require buffering into a complete message before validation

**Additional context**
Conversion from `json` to `avro` (for example) is much more challenging to implement incrementally without buffering the complete message, so we should separate the concepts of `validator` and `converter`, supporting `converters` only at the `kafka` `cache` where we already have a view of the complete message by design.

**Tasks**
  - [x] Separate the concepts of `Validator` and `Converter` in Java APIs
  - [x] `avro` `converter` should only be configurable in `kafka` `cache` by schema (not other protocols)
  - [x] `protobuf` `converter` should only be configurable in `kafka` `cache` by schema (not other protocols)
  - [x] all `validators` should only be configurable on `HTTP` and `MQTT` by schema
  - [x] both `validators` and `converters` should be configurable on `Kafka` by schema
  - [x] implement `string` fragmented validator
  - [x] implement `integer` fragmented validator
  - [x] implement `json` fragmented validator
