### ISSUE TITLE
Support idempotent `mqtt` `qos 2` publish to `kafka`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#677]
**Describe the desired outcome from the user's perspective**
As an MQTT developer, I want to be able to publish QoS 2 messages to Kafka.

**Acceptance criteria**
 - same zilla instance mqtt qos2 publish is idempotent before publish complete
 - different zilla instance mqtt qos2 publish is idempotent before publish complete

**Additional context**
[MQTT v3.1.1 QoS 2 Exactly Once Delivery](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718102)
[MQTT v5 QoS 2 Exactly Once Delivery](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901237)

**Tasks**
  - [x] Support `producerId`, `epoch` and message `sequence` in `kafka` binding for `produce` and `merged` streams
  - [x] Determine how to associate `kafka` `producerId` with `mqtt` `clientId` (state? v5 clientId? session?)
  - [x] Determine how to handle distinct `producerId` stream fan-in at `kafka` `cache_server` to shared `produce` stream
  - [x] Determine how to map `mqtt` `packetId` to `kafka` message `sequence` (state? sequence? gaps?)
