### ISSUE TITLE
Support observability of zilla engine internal streams

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#678]
**Describe the desired outcome from the user's perspective**
As a developer, I want to see how protocols are being used by `zilla` in the bindings I have configured via `zilla.yaml`.

**Acceptance criteria**
 - extract trace of streams from zilla engine while started or stopped
 - ability to dissect wire protocols such as HTTP, MQTT, Kafka, TLS, etc
 - ability to dissect zilla shared memory protocol, including extensions
 - ability to search by dissected protocol fields, including extensions

**Additional context**
Evolve `zilla dump` command to capture the zilla shared memory protocol explicitly, layered under the raw protocols such as HTTP, MQTT, Kafka, TLS, etc.

**Tasks**
  - [x] https://github.com/aklivity/zilla/pull/596
  - [x] https://github.com/aklivity/zilla/pull/635
  - [x] https://github.com/aklivity/zilla/pull/646
  - [x] https://github.com/aklivity/zilla/pull/652
  - [x] https://github.com/aklivity/zilla/pull/660
  - [x] https://github.com/aklivity/zilla/pull/695
  - [x] https://github.com/aklivity/zilla/pull/706
  - [x] https://github.com/aklivity/zilla/pull/723
