### ISSUE TITLE
Support `asyncapi` `http` response validation

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#683]
**Describe the desired outcome from the user's perspective**
As an AsyncAPI consumer, I want to configure `zilla` to validate `http` responses consistent with an `AsyncAPI` specification.

**Acceptance criteria**
 - `generate` command includes `http` response validation for `asyncapi`
 - `http` `server` binding responses are validated and replaced if invalid
 - `http` `client` binding responses are validated and replaced if invalid

**Additional context**
None

**Tasks**
 - [ ] Integrate `http` `server` binding response validation
 - [ ] Integrate `http` `client` binding response validation
 - [ ] Include `http` response validation in `generate` command output for `asyncapi` specification (`http`)

**Comment by attilakreiner** [comment]
AsyncApi reference does not seem to provide a way to define http response status code. I posted the question on AsnycApi slack: https://asyncapi.slack.com/archives/C34F2JV0U/p1705059814234959 
Turns out it's a missing feature that already has an issue https://github.com/asyncapi/bindings/issues/234 and a PR https://github.com/asyncapi/bindings/pull/235

**Comment by jfallows** [comment]
This is no longer blocked, see https://github.com/asyncapi/bindings/issues/234.
