### ISSUE TITLE
Support obtaining `protobuf` schemas from `schema registry` for `grpc` services

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#697]
**Describe the desired outcome from the user's perspective**
As a developer, I want to deploy updated `protobuf` schemas for `grpc` services and `protobuf` message validation without having to restart Zilla.

**Acceptance criteria**
 - `grpc` binding can retrieve `protobuf` schemas from `schema registry`
 - updated `protobuf` schema retrieved when `schema registry` cache `max-age` elapses

**Additional context**
None

**Tasks**
 - [ ] Integrate `catalog` with `grpc` binding to obtain `protobuf` schemas
 - [ ] Update `grpc` binding reference docs
 - [ ] Update `grpc` binding configurations in `zilla-examples`

**Comment by dudo** [comment]
Would this add the [magic byte](https://www.confluent.io/blog/how-to-fix-unknown-magic-byte-errors-in-apache-kafka/) to the message?

**Comment by jfallows** [comment]
> Would this add the [magic byte](https://www.confluent.io/blog/how-to-fix-unknown-magic-byte-errors-in-apache-kafka/) to the message?

@dudo The `grpc` binding currently produces raw protobuf messages towards the `grpc-kafka` binding, and will continue to maintain compatibility even when fetching the protobuf schema from `schema-registry` catalog in `zilla.yaml`.

However, specifying the type of messages on the topic in `kafka` `cache_client` binding using `schema-registry` catalog will prefix the `magic byte`, the `schema id` and `message indexes` onto the kafka topic, allowing a Kafka client with protobuf serdes and schema registry to full deserialize the message.
