### ISSUE TITLE
Use `model` and `view` when describing the message type

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#750]
**Is your feature request related to a problem? Please describe.**
Describe the message type using unique naming to not conflate other aspects of the zilla config like a binding's `type`.

**Describe the solution you'd like**
Use the word `model` when referring to the message type as it is stored and transmitted. Use the word `view` when describing a the message type after the stored message is converted from or to.

generic example
```
key:
  model: string
value:
  model: protobuf
  view: json
```

**Additional context**
Specific examples from the bindings this change may affect.

Kafka:
```
type: kafka
kind: cache_server
options:
  topics:
    - name: my_topic
      value:
        model: protobuf
        view: json
        catalog:
          my_registry:
            - id: 1
```

HTTP:
```
type: http
kind: server
options:
  requests:
    - path: /hello
      method: GET
      content:
        model: json
    - path: /valid/{category}/{id}
      method: POST
      content-type:
        - application/json
      headers:
        code:
          model: string
          length: 13
      params:
        path:
          category:
            model: string
            length: 13
          id:
            model: integer
        query:
          page:
            model: integer
      content:
        model: json
```

MQTT
```
type: mqtt
kind: server
options:
  topics:
    - name: sensor/one
      content:
        model: json
```

**Tasks**
  - [x] refactor `types-*` modules to `model-*` modules
  - [x] unify `ValidatorFactorySpi` and `ConverterFactorySpi` to `ModelFactorySpi`
    - unify `Validator` and `Converter` to `Model`
    - unify `ValidatorContext` and `ConverterContext` to `ModelContext`
    - retain `ValidatorHandler` and `ConverterHandler` obtained from `ModelContext`
    - consider implications of unifying `ValidatorConfig` and `ConverterConfig` into `ModelConfig`, restrict `view` via schema?
  - [x] update `http` and `mqtt` reference docs to allow only `validators` (not `converters`) in type information (using `model` `view` terms now instead)
 - [x] document `protobuf` support in zilla reference (using `model` `view` terms)
